### PR TITLE
fix: ensure 2-decimal rounding on all floating-point stat calculations

### LINKED ISSUE #193: Ensure good rounding with number manipulation
Avoir number like 36,0000000005 and ensure two decimals numbers rouding

### PR DESCRIPTION
**Pull request by cegerard**
Introduce roundTo2() utility and apply it to buff/debuff values,
healing amounts, and poison/burn damage values to prevent
imprecision like 3.3000000000000003 propagating into fight reports.

Fixes #193
https://claude.ai/code/session_01MnnPVDhMe1RNSzWgmYuywM

### CODE REVIEW

File: src/fight/tools/round.ts [hunk 1]
```diff
@@ -0,0 +1,3 @@
+export function roundTo2(value: number): number {
```
Comment (cegerard) [inline src/fight/tools/round.ts]: rename to round2
