### PR TITLE
fix(types): remove outer { kind: StepKind } & wrapper from Step union

### LINKED ISSUE #69: [types] Remove outer { kind: StepKind } & wrapper from Step union
[types] Remove outer { kind: StepKind } & wrapper from Step union — it widens the discriminator

### PR DESCRIPTION
**Pull request by cegerard**
The outer intersection widened the discriminator for union members that
lacked their own kind literal (DamageReport, StatusChangeReport,
WinnerReport, StateEffectReport), preventing TypeScript from narrowing
on Step.kind.

Each Step union member now carries its own specific kind literal,
making the union a proper discriminated union. A narrowing cast is
added in action-stage where kind is a union type at the push site.

Closes #69

https://claude.ai/code/session_01LAGU1RwpnAJNWY6iMx25sQ

### CODE REVIEW

File: src/fight/core/fight-simulator/@types/step.ts [hunk 1]
```diff
@@ -28,16 +28,16 @@ export enum StepKind {
...
 }
 
-export type Step = { kind: StepKind } & (
-  | StatusChangeReport
-  | DamageReport
+export type Step =
+  | ({ kind: StepKind.StatusChange } & StatusChangeReport)
+  | ({ kind: StepKind.Attack } & DamageReport)
+  | ({ kind: StepKind.SpecialAttack } & DamageReport)
   | HealingReport
```
Comment (cegerard) [inline src/fight/core/fight-simulator/@types/step.ts:35]: Why this one has not been refactored with an object with a healing kind.

File: src/fight/core/fight-simulator/@types/step.ts [hunk 2]
```diff
@@ -28,16 +28,16 @@ export enum StepKind {
...
+  | ({ kind: StepKind.FightEnd } & WinnerReport)
+  | ({ kind: StepKind.StateEffect } & StateEffectReport)
   | BuffReport
   | DebuffReport
   | BuffRemovedReport
   | TargetingOverrideReport
   | TargetingRevertedReport
-  | EffectRemovedReport
-);
+  | EffectRemovedReport;
```
Comment (cegerard) [inline src/fight/core/fight-simulator/@types/step.ts:43]: Why there is no refactoring with an object with  fixed kind value ?
